optimize-sub-barrier
yedf/dtm pull request #100
Opened 2021-12-19 06:51 UTC by wuqinqiang

#91

2021-12-19 07:13 UTC, yedf2 commented
您好，看了您的代码，您的新代码，思路也很好。从代码简洁的交付来看，不拆开单独函数，而是在一个函数里，代码更少。如果把注释写清楚，貌似就可以很清晰了。
另外map的方式比多个if更简洁

2021-12-19 09:03 UTC, wuqinqiang commented
个人一些不成熟观点:拆开后代码相对来说虽然会多一点，但是把部分责任拆出去，代码看着会舒服一点。map在条件多的情况下确实比if简洁一些。
有个疑惑，如果是这样的话，我其实不太明白您是想让我们优化哪一块？

2021-12-19 09:28 UTC, yedf2 commented
现有的代码虽然也不长，但是在理解上，不如最新的子事务屏障叙述来的清晰易理解

希望的优化改动可能就是三四行代码，但是更容易理解，让其他人更容易去实现其他语言的SDK

2021-12-19 12:42 UTC, wuqinqiang commented
> 现有的代码虽然也不长，但是在理解上，不如最新的子事务屏障叙述来的清晰易理解
> 
> 希望的优化改动可能就是三四行代码，但是更容易理解，让其他人更容易去实现其他语言的SDK

看了一下原理介绍那，改了一下，不知道是不是你说的意思。

2021-12-19 13:03 UTC, yedf2 commented
对，正是这个意思，不过有些小bug，没有通过自动化测试，需要修改一下

2021-12-19 15:58 UTC, yedf2 commented
本地就可以跑测试，文档已更新，测试命令为
go test ./...

2021-12-19 16:17 UTC, wuqinqiang commented
> 本地就可以跑测试，文档已更新，测试命令为 go test ./...
额嗯，跑了几次自己才想起来可以本地跑，
但是本地有个不合理的地方，我提个issue你看下。

2021-12-20 07:50 UTC, yedf2 requested changes

2021-12-20 07:50 UTC, yedf2 commented on dtmcli/barrier.go
> +		bb.BranchID, bb.Op, "", bb.Op)
为什么修改了BarrierID的类型，为什么在这个地方把barrierid变成了空字符串？

假如一个服务当中，访问多个数据源，那么使用多个barrier.Call就行了。但是改成了固定值，这样就不行了。未来我会加上这样的测试用例以及例子

2021-12-20 09:30 UTC, wuqinqiang commented on dtmcli/barrier.go
> +		bb.BranchID, bb.Op, "", bb.Op)
> 为什么修改了BarrierID的类型，为什么在这个地方把barrierid变成了空字符串？
> 
> 假如一个服务当中，访问多个数据源，那么使用多个barrier.Call就行了。但是改成了固定值，这样就不行了。未来我会加上这样的测试用例以及例子

修改它的类型是因为本身数据库就是string,为了 对齐。

变成空字符串是因为看了代码，感觉目前这个字段是没有被赋予业务逻辑中，所以索引使用空字符串了。

2021-12-22 13:36 UTC, closed without merging